### ISSUE TITLE
LunaticPatch source

### ISSUE THREAD

**Issue by gelatinoustesseract** [EmpioDavion/LunaticModdingAPI#5]
I don't know where to put this but I need ModMagic.OnCast() to work and the source for LunaticPatch isn't in the repository.

**Comment by gelatinoustesseract** [comment]
I remembered that I can make my own patch which references my own script assembly.

**Comment by EmpioDavion** [comment]
Hi, I've made the repository for LunaticPatch public here https://github.com/EmpioDavion/LunaticPatch
The LunaticPatch project is built using netstandard, while LunaticPatch40 is built using net40.
The reason for two projects is that harmony transpilers only work in net40, while netstandard is needed for communication with Lunatic and Unity.
