### ISSUE TITLE
Build version is old.

### ISSUE THREAD

**Issue by gelatinoustesseract** [EmpioDavion/LunaticModdingAPI#6]
I'd like to release a mod, but it requires features and fixes from the current version of Lunatic to work properly.
When you have the time, could you update the repository build?
I'd include Lunatic with the mod but I'm not sure about the permissions on doing that.

**Comment by EmpioDavion** [comment]
I've updated the build dlls. I was able to load the template mod fine running the latest version of Lunacid.
If there are any issues let me know, or if it's working fine so I can close the issue.

**Comment by gelatinoustesseract** [comment]
It works. Thank you.
